# Generated by Django 3.0.1 on 2020-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITYW', '0002_auto_20200713_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='iteminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_kind', models.CharField(max_length=20)),
                ('item_sn', models.CharField(max_length=50)),
                ('item_now_user', models.CharField(max_length=50)),
                ('item_location', models.CharField(default='', max_length=50)),
                ('item_info', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='hardwareinfo',
        ),
        migrations.AddField(
            model_name='useritemsinfo',
            name='user_location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
