# Generated by Django 3.0.1 on 2020-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITYW', '0005_auto_20200713_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchangeinfo',
            name='item_now_user_workid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_now_user_workid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useritemsinfo',
            name='user_workid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
