# Generated by Django 3.0.1 on 2020-07-14 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ITYW', '0006_auto_20200713_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='item_inbound_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
