# Generated by Django 3.0.1 on 2020-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITYW', '0007_iteminfo_item_inbound_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='item_stock_location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
