# Generated by Django 3.0.1 on 2020-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITYW', '0009_itemstock_item_destory_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_notebook_sn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_pad_sn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_pc_sn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_phone_num',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_phone_sn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_qianniu_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useritemsinfo',
            name='user_wechat_name',
            field=models.CharField(max_length=500),
        ),
    ]
